# Schema for the configuration files of the Formation 2 module.
formation2.settings:
  type: config_object
  label: 'Formation 2 settings'
  mapping:
    reference_date:
      type: date
      label: 'Date de reference'
    default_name:
      type: string
      label: Nom par défaut
