# Schema for the configuration files of the Instant Message module.
instant_message.settings:
  type: config_object
  label: 'Instant Message settings'
  mapping:
    read_retention:
      type: int
      label: 'Read retention'
