<?php

/**
 * implements HOOK_help
 */
function formation1_help(
  $route_name,
  \Drupal\Core\Routing\RouteMatchInterface $route_match
) {
  switch ($route_name) {
    case 'help.page.formation1':
      return '<p>Ceci est la page d\'aide de notre module.</p>';
  }
}

/**
 * Implements HOOK_theme.
 *
 * Définit les fichiers template (twig) introduit par ce module.
 */
function formation1_theme() {
  return [
    'formation1-exemple1' => [
      'template' => 'formation1-exemple1', // optional as template name equals theme key
      'variables' => [
        'var1' => 123,
        'var2' => '',
      ]
    ]
  ];
}
